# Generated by Django 5.1.2 on 2024-11-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='course',
            field=models.ForeignKey(blank=True, default=None, help_text='The course to which the quiz belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning_materials.course'),
        ),
    ]
