# Generated by Django 5.1.2 on 2024-10-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='end',
            new_name='end_page',
        ),
        migrations.RenameField(
            model_name='quizmodel',
            old_name='start',
            new_name='start_page',
        ),
    ]
