# Generated by Django 5.1.2 on 2024-11-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='course',
            field=models.ForeignKey(blank=True, default=None, help_text='The course to which the cardset belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardsets', to='learning_materials.course'),
        ),
    ]
