# Generated by Django 5.1.2 on 2024-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='subject',
            field=models.CharField(default='Unknown', help_text='The subject of the quiz', max_length=1000),
        ),
    ]
