# Generated by Django 5.1.1 on 2024-10-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_materials", "0002_chathistory"),
        ("learning_materials", "0002_flashcardmodel_proficiency_and_more"),
    ]

    operations = []
