# Generated by Django 5.1.2 on 2024-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0002_quizmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='end_page',
            field=models.IntegerField(blank=True, help_text='The ending page of the quiz', null=True),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='start_page',
            field=models.IntegerField(blank=True, help_text='The starting page of the quiz', null=True),
        ),
    ]
