# Generated by Django 5.1.2 on 2024-10-21 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0002_rename_end_quizmodel_end_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='user',
            field=models.ForeignKey(help_text='The user who created this cardset', on_delete=django.db.models.deletion.CASCADE, related_name='cardsets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flashcardmodel',
            name='cardset',
            field=models.ForeignKey(help_text='The cardset to which the flashcard belongs', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning_materials.cardset'),
        ),
    ]
