# Generated by Django 5.1.2 on 2024-12-17 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_cardset_created_at_cardset_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='urls', to='learning_materials.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_urls',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
