# Generated by Django 5.1.2 on 2024-10-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_alter_cardset_user_alter_flashcardmodel_cardset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestionmodel',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz to which the multiple-choice question belongs', on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='learning_materials.quizmodel'),
        ),
        migrations.AlterField(
            model_name='questionanswermodel',
            name='quiz',
            field=models.ForeignKey(help_text='The quiz to which the question-answer pair belongs', on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='learning_materials.quizmodel'),
        ),
    ]
