# Generated by Django 5.1.2 on 2024-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_alter_quizmodel_end_page_alter_quizmodel_start_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='subject',
            field=models.CharField(default='Unknown', help_text='The subject of the cardset', max_length=1000),
        ),
    ]
