# Generated by Django 5.1.2 on 2024-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0004_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurl',
            name='name',
            field=models.CharField(default='URL NOT NAMED', max_length=255),
        ),
    ]
