# Generated by Django 5.1.2 on 2025-01-07 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0005_userurl_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1024)),
                ('name', models.CharField(default='VIDEO NOT NAMED', max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='videos', to='learning_materials.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]