# Generated by Django 5.1.2 on 2025-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0008_course_language_course_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preferred_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]