# Generated by Django on 2025-03-16 10:43

import uuid
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0011_migrate_ids_to_uuid'),
    ]

    operations = [
        # --- Update Cardset ---
        # Remove the old primary key field (an integer).
        migrations.RemoveField(
            model_name='cardset',
            name='id',
        ),
        # Rename new_id to id.
        migrations.RenameField(
            model_name='cardset',
            old_name='new_id',
            new_name='id',
        ),
        # Re-establish the primary key with the proper settings.
        migrations.AlterField(
            model_name='cardset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
        # --- Update FlashcardModel ---
        # Remove the old primary key field.
        migrations.RemoveField(
            model_name='flashcardmodel',
            name='id',
        ),
        # Rename new_id to id.
        migrations.RenameField(
            model_name='flashcardmodel',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='flashcardmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        # Now fix the foreign key field.
        # First, remove the old foreign key column (which still holds integer values).
        migrations.RemoveField(
            model_name='flashcardmodel',
            name='cardset',
        ),
        # Then, rename the temporary foreign key field to "cardset".
        migrations.RenameField(
            model_name='flashcardmodel',
            old_name='new_cardset',
            new_name='cardset',
        ),
        # Finally, re-add the foreign key constraint so that FlashcardModel.cardset now points to Cardset.
        migrations.AlterField(
            model_name='flashcardmodel',
            name='cardset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flashcards',
                to='learning_materials.cardset',
                help_text='The cardset to which the flashcard belongs'
            ),
        ),
        
        # --- Update MultipleChoiceQuestionModel ---
        migrations.RemoveField(
            model_name='multiplechoicequestionmodel',
            name='id',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestionmodel',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
        # --- Update QuestionAnswerModel ---
        migrations.RemoveField(
            model_name='questionanswermodel',
            name='id',
        ),
        migrations.RenameField(
            model_name='questionanswermodel',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='questionanswermodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
        # --- Update QuizModel ---
        migrations.RemoveField(
            model_name='quizmodel',
            name='id',
        ),
        migrations.RenameField(
            model_name='quizmodel',
            old_name='new_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]