# Generated by Django 5.1.2 on 2025-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0012_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='scores',
            field=models.JSONField(blank=True, default=list, help_text='List of scores from all attempts'),
        ),
    ]
