# Generated by Django 5.1.11 on 2025-07-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_document_file_hash_document_graph_id_and_more'),
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='courses.document'),
        ),
        migrations.DeleteModel(
            name='DocumentUpload',
        ),
    ]
