services:
  backend:
    build:
      context: ./src
    container_name: backend 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
      - zookeeper
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=tutoraidb
      - DATABASE_USER=tutoraiuser
      - DATABASE_PASSWORD=tutoraipassword
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - RAG_DATABASE_SYSTEM=${RAG_DATABASE_SYSTEM}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - BASE_URL_SCRAPER=http://scraper-service:8080
      - BASE_URL_FRONTEND=${BASE_URL_FRONTEND}
      - DEBUG=${DEBUG}
    networks:
      - tutorai_network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tutoraidb
      - POSTGRES_USER=tutoraiuser
      - POSTGRES_PASSWORD=tutoraipassword
    networks:
      - tutorai_network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    hostname: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - tutorai_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - tutorai_network

volumes:
  postgres_data:
  static_volume:

networks:
  tutorai_network:
    external: true
