apiVersion: v2
name: aksio-backend
description: Aksio Backend Helm Chart for Kubernetes deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - aksio
  - backend
  - django
  - education
  - ai

home: https://aksio.app
sources:
  - https://github.com/your-org/aksio-backend

maintainers:
  - name: Aksio Team
    email: team@aksio.app

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: ingress-nginx
    version: "4.x.x"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled

annotations:
  category: Backend