# Generated by Django 5.1.2 on 2024-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, default="N/A", max_length=15, null=True),
        ),
    ]
