apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tutor-service.name" . }}-config
  labels:
    {{- include "tutor-service.labels" . | nindent 4 }}
data:
  # Add your non-sensitive configurations here
  # Example:
  # MY_SETTING: "some value"
