# Generated by Django 5.1.11 on 2025-07-21 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_chat_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='graph_id',
            field=models.CharField(blank=True, db_index=True, help_text='Knowledge graph identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_chunks',
            field=models.PositiveIntegerField(default=0, help_text='Number of processed chunks'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0, help_text='Total number of text chunks'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_edges',
            field=models.PositiveIntegerField(default=0, help_text='Number of knowledge graph edges'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_nodes',
            field=models.PositiveIntegerField(default=0, help_text='Number of knowledge graph nodes'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_file_ha_3bbf78_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['graph_id'], name='documents_graph_i_b81389_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'processing_status'], name='documents_course__fa5b72_idx'),
        ),
    ]
