# Generated by Django 5.1.2 on 2024-10-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_page', models.IntegerField(default=1)),
                ('end_page', models.IntegerField(default=1)),
                ('subject', models.CharField(blank=True, help_text='The subject of the document', max_length=100)),
                ('learning_goals', models.JSONField(blank=True, default=list, help_text='List of learning goals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
