# Generated by Django 5.1.1 on 2024-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionhistory'),
    ]

    operations = [
    ]
