# Generated by Django 5.1.1 on 2024-10-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_name',
            new_name='name',
        ),
    ]
