# Generated by Django 5.1.1 on 2024-10-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241006_1342'),
    ]

    operations = [
    ]
