# Generated by Django 5.1.1 on 2024-10-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20241006_1346'),
    ]

    operations = [
    ]
