# Generated by Django 5.1.1 on 2024-10-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20241007_1540'),
    ]

    operations = [
    ]
