replicaCount: 2

image:
  tag: latest-staging

service:
  type: ClusterIP

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env:
  ENVIRONMENT: staging
