name: Build and Push Docker Image

# Only runs if CI was successful and on the main branch
on:
 workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    # Only runs if CI was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Environment Tag
        id: env_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest-prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "tag=latest-staging" >> $GITHUB_OUTPUT
          else
            echo "tag=latest-dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/the-tutorai-project/tutor-service:${{ steps.env_tag.outputs.tag }} ./src/
          docker push ghcr.io/the-tutorai-project/tutor-service:${{ steps.env_tag.outputs.tag }}
