name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest Docker image and restart services
        run: |
          docker compose down
          docker compose pull backend
          docker compose build backend
          docker compose run backend python manage.py migrate
          docker compose up -d backend